version: "3"
services:
  couchdb:
    image: couchdb:2.3.0
    environment:
      - "COUCHDB_USER=admin"
      - "COUCHDB_PASSWORD=proofofconcept"
    ports:
      - "5984:5984"
    labels:
      - traefik.enable=true
      - traefik.backend=couchdb
      - traefik.http.routers.api.rule=Host(`monitor.redcanari.com`)
      - traefik.http.routers.api.service=api-internal
      - traefik.port=5984
  node:
    image: node:11
    command: npm start
    working_dir: "/app"
    volumes:
      - ".:/app"
    ports:
      - "4243:3000"
    depends_on:
      - couchdb

  auth:
    build: ./auth
    hostname: auth
    #env_file: ./server1/.env
    ports:
      - "4000:4000"

  traefik:
    image: traefik:v1.7.16
    container_name: traefik
    ports:
      - "8085:80"
      - "8086:8080"
      - "8080:8080" # <== :8080 is where the dashboard runs on
      - "443:443" # <== https
    volumes:
      - ./letsencrypt:/letsencrypt # <== Volume for certs (TLS)
      - ./traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - traefik.enable=true # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      - traefik.http.routers.api.service=api@internal # <== Enabling the api to be a service to access
      - traefik.http.routers.traefik.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)
      - --entryPoints.http.address=:80
      - --entrypoints.http.http.middlewares=traefik-forward-auth # "default-traefik-forward-auth" on kubernetes
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    build: ../
    command: ./traefik-forward-auth --rule.1.action=allow --rule.1.rule="Path(`/`)"
    environment:
      - SECRET=4b7b31abdf3fcf13f2ee9a4a16d6d43e
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=https://login.microsoftonline.com/c95ac181-ea4a-4f44-98d5-6bcdd472ba6d/v2.0
      - PROVIDERS_OIDC_CLIENT_ID=83500ba7-355f-46ac-9b49-66d3f62d257e
      - PROVIDERS_OIDC_CLIENT_SECRET=9430caaf-04da-420c-99ab-84cfddc1b2db
    labels:
      - --url-path= https://localhost:3000
      - --default-provider= oidc
      - --providers.oidc.issuer-url= https://login.microsoftonline.com/c95ac181-ea4a-4f44-98d5-6bcdd472ba6d/v2.0
      - --providers.oidc.client-id= 83500ba7-355f-46ac-9b49-66d3f62d257e
      - --providers.oidc.client-secret= 9430caaf-04da-420c-99ab-84cfddc1b2db
      # INSECURE_COOKIE is required if not using a https entrypoint
      - INSECURE_COOKIE=true
      - LOG_LEVEL=debug
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.middlewares=traefik-forward-auth"
      - "traefik.http.routers.whoami.rule=Host(`https://localhost:3000`)"
      # This example uses "Selective Authentication"
      - "traefik.frontend.rule=Host:whoami.localhost.com"
