version: "3"
services:
  couchdb:
    image: couchdb:2.3.0
    environment:
      - "COUCHDB_USER=admin"
      - "COUCHDB_PASSWORD=proofofconcept"
    ports:
      - "5984:5984"

  node:
    image: node:11
    command: npm start
    working_dir: "/app"
    volumes:
      - ".:/app"
    ports:
      - "4243:3000"
    depends_on:
      - couchdb

  auth:
    build: ./auth
    hostname: auth
    #env_file: ./server1/.env
    ports:
      - "4000:4000"
